name: echo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.1
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  google_sign_in: ^6.3.0
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.3
  image_picker: ^1.1.2
  table_calendar: ^3.0.9
  intl: ^0.20.2
  path: ^1.9.1
  uuid: ^4.5.1
  just_audio: ^0.10.2
  path_provider: ^2.1.5
  dio: ^5.8.0+1
  video_player: ^2.9.5
  chewie: ^1.11.3
  record: ^6.0.0
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/profile/
