import 'dart:io';
import 'package:echo/features/auth/provider/auth_provider.dart';
import 'package:echo/features/media_upload/provider/media_upload_provider.dart';
import 'package:echo/features/media_upload/services/storage_service.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:echo/features/date_detail/provider/log_entries_provider.dart';
import 'package:just_audio/just_audio.dart';

// Transcription UI after recording audio
class TranscriptionSheet extends ConsumerStatefulWidget {
  final String audioPath;
  final DateTime date;

  const TranscriptionSheet({
    super.key,
    required this.audioPath,
    required this.date,
  });

  @override
  ConsumerState<TranscriptionSheet> createState() => _TranscriptionSheetState();
}

class _TranscriptionSheetState extends ConsumerState<TranscriptionSheet> {
  final TextEditingController _titleController = TextEditingController();
  final TextEditingController _tagController = TextEditingController();
  String _transcription =
      ""; // In a real app, this would come from a transcription service
  bool _isLoading = true;
  bool _isSaving = false;
  final List<String> _tags = [];
  late Duration _audioDuration;

  @override
  void initState() {
    super.initState();
    _processAudio();
  }

  @override
  void dispose() {
    _titleController.dispose();
    _tagController.dispose();
    super.dispose();
  }

  // Add a tag to the list
  void _addTag() {
    final tag = _tagController.text.trim();
    if (tag.isNotEmpty && !_tags.contains(tag)) {
      setState(() {
        _tags.add(tag);
        _tagController.clear();
      });
    }
  }

  // Remove a tag from the list
  void _removeTag(String tag) {
    setState(() {
      _tags.remove(tag);
    });
  }

  Future<void> _processAudio() async {
    setState(() => _isLoading = true);
    try {
      // Get the audio duration
      final player = AudioPlayer();
      await player.setFilePath(widget.audioPath);
      _audioDuration = player.duration ?? const Duration(seconds: 30);

      // Simulate transcription process
      await Future.delayed(const Duration(seconds: 1));

      // Generate mock transcription and title
      _transcription =
          "This is a sample transcription of the audio recording. This would be generated by a speech-to-text service.";
      _titleController.text =
          "Audio Recording ${DateTime.now().toString().substring(0, 16)}";
    } catch (e) {
      debugPrint('Error getting audio duration: $e');
      _audioDuration = const Duration(seconds: 30);
    } finally {
      setState(() => _isLoading = false);
    }
  }

  Future<void> _saveAudioEntry() async {
    final title = _titleController.text.trim();
    if (title.isEmpty) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(const SnackBar(content: Text('Please enter a title')));
      return;
    }

    setState(() {
      _isSaving = true;
    });

    try {
      // Get the current user ID and username
      final authState = ref.read(authStateProvider);
      final userId = authState.valueOrNull?.id;
      final username = authState.valueOrNull?.displayName ?? 'user';

      if (userId == null) {
        throw Exception('User not authenticated');
      }

      // Upload to Firebase Storage using our simplified service
      final storageService = ref.read(storageServiceProvider);
      final audioUrl = await storageService.uploadMedia(
        mediaFile: File(widget.audioPath),
        userId: userId,
        username: username,
        mediaType: 'audios',
      );

      if (audioUrl == null) {
        throw Exception('Failed to upload audio');
      }

      // Create a new audio log entry with tags
      await ref
          .read(logEntriesProvider.notifier)
          .addAudioLogEntry(
            audioUrl: audioUrl,
            transcription: _transcription,
            duration: _audioDuration,
            title: title,
            timestamp: DateTime(
              widget.date.year,
              widget.date.month,
              widget.date.day,
              DateTime.now().hour,
              DateTime.now().minute,
              DateTime.now().second,
            ),
            tags: _tags,
          );

      // Close the sheet
      if (mounted) {
        Navigator.pop(context);
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Audio saved successfully')),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text('Error saving audio: $e')));
      }
    } finally {
      if (mounted) {
        setState(() {
          _isSaving = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    // Watch the upload state to show when uploading
    final uploadState = ref.watch(mediaUploadProvider);
    final isUploading =
        uploadState.isLoading && uploadState.mediaType == 'audios';
    final primaryColor = const Color(0xFF6E61FD);

    return Container(
      height: MediaQuery.of(context).size.height * 0.7,
      padding: const EdgeInsets.all(20),
      decoration: const BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      child:
          _isLoading
              ? const Center(
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    CircularProgressIndicator(
                      valueColor: AlwaysStoppedAnimation<Color>(
                        Color(0xFF6E61FD),
                      ),
                    ),
                    SizedBox(height: 16),
                    Text(
                      'Transcribing audio...',
                      style: TextStyle(
                        fontSize: 16,
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ],
                ),
              )
              : SingleChildScrollView(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // Drag handle
                    Center(
                      child: Container(
                        width: 40,
                        height: 4,
                        decoration: BoxDecoration(
                          color: Colors.grey[300],
                          borderRadius: BorderRadius.circular(10),
                        ),
                      ),
                    ),
                    const SizedBox(height: 20),

                    // Title field
                    TextField(
                      controller: _titleController,
                      decoration: InputDecoration(
                        labelText: 'Title',
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(12),
                        ),
                        focusedBorder: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(12),
                          borderSide: const BorderSide(
                            color: Color(0xFF6E61FD),
                            width: 2,
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(height: 20),

                    // Tags section
                    const Text(
                      'Tags',
                      style: TextStyle(
                        fontSize: 16,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    const SizedBox(height: 8),

                    // Tag input and add button
                    Row(
                      children: [
                        Expanded(
                          child: TextField(
                            controller: _tagController,
                            decoration: InputDecoration(
                              hintText: 'Add a tag',
                              border: OutlineInputBorder(
                                borderRadius: BorderRadius.circular(12),
                              ),
                              focusedBorder: OutlineInputBorder(
                                borderRadius: BorderRadius.circular(12),
                                borderSide: const BorderSide(
                                  color: Color(0xFF6E61FD),
                                  width: 2,
                                ),
                              ),
                              contentPadding: const EdgeInsets.symmetric(
                                horizontal: 12,
                                vertical: 8,
                              ),
                            ),
                            onSubmitted: (_) => _addTag(),
                          ),
                        ),
                        const SizedBox(width: 8),
                        IconButton(
                          onPressed: _addTag,
                          icon: const Icon(
                            Icons.add_circle,
                            color: Color(0xFF6E61FD),
                            size: 36,
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 12),

                    // Display tags as a wrapped list of chips
                    Wrap(
                      spacing: 8,
                      runSpacing: 8,
                      children:
                          _tags
                              .map(
                                (tag) => Chip(
                                  label: Text(tag),
                                  deleteIcon: const Icon(Icons.close, size: 16),
                                  onDeleted: () => _removeTag(tag),
                                  backgroundColor: const Color(
                                    0xFF6E61FD,
                                  ).withOpacity(0.2),
                                ),
                              )
                              .toList(),
                    ),
                    const SizedBox(height: 20),

                    // Transcription
                    const Text(
                      'Transcription',
                      style: TextStyle(
                        fontSize: 16,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    const SizedBox(height: 8),

                    // Fixed height container for transcription
                    Container(
                      height: 150,
                      padding: const EdgeInsets.all(12),
                      decoration: BoxDecoration(
                        color: Colors.grey[100],
                        borderRadius: BorderRadius.circular(12),
                        border: Border.all(color: Colors.grey[300]!),
                      ),
                      child: SingleChildScrollView(child: Text(_transcription)),
                    ),

                    // Simple upload status indicator
                    if (isUploading) ...[
                      const SizedBox(height: 20),
                      Row(
                        children: [
                          const SizedBox(width: 8),
                          SizedBox(
                            width: 16,
                            height: 16,
                            child: CircularProgressIndicator(
                              strokeWidth: 2,
                              valueColor: AlwaysStoppedAnimation<Color>(
                                primaryColor,
                              ),
                            ),
                          ),
                          const SizedBox(width: 8),
                          Text(
                            'Uploading audio...',
                            style: TextStyle(fontSize: 14, color: primaryColor),
                          ),
                        ],
                      ),
                    ],

                    const SizedBox(height: 20),

                    // Save button
                    SizedBox(
                      width: double.infinity,
                      height: 50,
                      child: ElevatedButton(
                        onPressed:
                            (_isSaving || isUploading) ? null : _saveAudioEntry,
                        style: ElevatedButton.styleFrom(
                          backgroundColor: const Color(0xFF6E61FD),
                          foregroundColor: Colors.white,
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(12),
                          ),
                          disabledBackgroundColor: Colors.grey[400],
                        ),
                        child:
                            _isSaving
                                ? const Row(
                                  mainAxisAlignment: MainAxisAlignment.center,
                                  children: [
                                    SizedBox(
                                      width: 20,
                                      height: 20,
                                      child: CircularProgressIndicator(
                                        strokeWidth: 2,
                                        valueColor:
                                            AlwaysStoppedAnimation<Color>(
                                              Colors.white,
                                            ),
                                      ),
                                    ),
                                    SizedBox(width: 12),
                                    Text(
                                      'Saving...',
                                      style: TextStyle(
                                        fontSize: 16,
                                        fontWeight: FontWeight.bold,
                                      ),
                                    ),
                                  ],
                                )
                                : const Text(
                                  'Save Entry',
                                  style: TextStyle(
                                    fontSize: 16,
                                    fontWeight: FontWeight.bold,
                                  ),
                                ),
                      ),
                    ),
                    const SizedBox(height: 10), // Add some bottom padding
                  ],
                ),
              ),
    );
  }
}
