// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzN4VUsNNz_HW6jI06x7yrdPbrrh07OSI',
    appId: '1:1007138815568:web:29ccc52f33da876d9f9b55',
    messagingSenderId: '1007138815568',
    projectId: 'echo-audio-journaling-app',
    authDomain: 'echo-audio-journaling-app.firebaseapp.com',
    storageBucket: 'echo-audio-journaling-app.firebasestorage.app',
    measurementId: 'G-RCR7ZDWB09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKZkUqKC08YMJWrPFBksIo0-7Bjto1KeA',
    appId: '1:1007138815568:android:28488d5c3cb92f6b9f9b55',
    messagingSenderId: '1007138815568',
    projectId: 'echo-audio-journaling-app',
    storageBucket: 'echo-audio-journaling-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzXaiNWJFHJKRf_rbidSjNKZexxWsgr5U',
    appId: '1:1007138815568:ios:c84b4282297276559f9b55',
    messagingSenderId: '1007138815568',
    projectId: 'echo-audio-journaling-app',
    storageBucket: 'echo-audio-journaling-app.firebasestorage.app',
    iosBundleId: 'io.echo.fluttergods.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzXaiNWJFHJKRf_rbidSjNKZexxWsgr5U',
    appId: '1:1007138815568:ios:c84b4282297276559f9b55',
    messagingSenderId: '1007138815568',
    projectId: 'echo-audio-journaling-app',
    storageBucket: 'echo-audio-journaling-app.firebasestorage.app',
    iosBundleId: 'io.echo.fluttergods.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzN4VUsNNz_HW6jI06x7yrdPbrrh07OSI',
    appId: '1:1007138815568:web:210238998c3102579f9b55',
    messagingSenderId: '1007138815568',
    projectId: 'echo-audio-journaling-app',
    authDomain: 'echo-audio-journaling-app.firebaseapp.com',
    storageBucket: 'echo-audio-journaling-app.firebasestorage.app',
    measurementId: 'G-80PKENC105',
  );
}
